#!/usr/bin/env sh

# Navigate between spaces
lalt - 1 : yabai -m space --focus 1
lalt - 2 : yabai -m space --focus 2
lalt - 3 : yabai -m space --focus 3
lalt - 4 : yabai -m space --focus 4
lalt - 5 : yabai -m space --focus 5
lalt - 6 : yabai -m space --focus 6
lalt - 7 : yabai -m space --focus 7
lalt - 8 : yabai -m space --focus 8
lalt - 9 : yabai -m space --focus 9

# Move windows between spaces
shift + lalt - 1 : yabai -m window --space 1
shift + lalt - 2 : yabai -m window --space 2

# Navigate between windows
lalt - h : yabai -m window --focus west || yabai -m display --focus west
lalt - j : yabai -m window --focus south || yabai -m display --focus south
lalt - k : yabai -m window --focus north || yabai -m display --focus north
lalt - l : yabai -m window --focus east || yabai -m display --focus easth

# Split
shift + lalt - s : yabai -m window --toggle split

